name: Release
concurrency:
  group: release-${{ github.repository }}

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: .

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build/load image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Containerfile
          push: false
          load: true
          tags: "app-image:${{ github.sha }}"

      - name: Lint with Dockle
        uses: erzz/dockle-action@v1
        with:
          image: app-image:${{ github.sha }}
          exit-code: 1
          failure-threshold: FATAL
          timeout: "10m"

      - name: Scan with Trivy
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: app-image:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: "10m"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ startsWith(github.event.ref, 'refs/tags/v') }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: .

      - name: Log in to GitHub CR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: metadata
        name: Gather image metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Release image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Containerfile
          push: true
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
