name: Release
concurrency:
  group: release-${{ github.repository }}

on:
  push:
    tags:
      - 'v*'

env:
  FILE_PATH: "Containerfile"
  IMAGE_NAME: fts-server
  REGISTRY: hub.opensciencegrid.org

jobs:
  lint-scan:
    name: Lint/scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: .

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "${{ env.FILE_PATH }}"
          load: true
          push: false
          tags: app-image:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Lint with Dockle
        uses: erzz/dockle-action@v1
        with:
          image: app-image:${{ github.sha }}
          exit-code: 1
          failure-threshold: FATAL
          timeout: "10m"

      - name: Scan with Trivy
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: app-image:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: "10m"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - lint-scan

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: .

      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      - id: metadata
        name: Gather image metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/slate/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Release image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "${{ env.FILE_PATH }}"
          push: true
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
